name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
 deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: cr.anikeen.cloud
        username: k3s
        password: ${{ secrets.REGISTRY_PASSWORD }}
