name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
 deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: cr.anikeen.cloud
        username: k3s
        password: ${{ secrets.REGISTRY_PASSWORD }}
